//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDP_Project.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/MyDBService")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Attractions", Namespace="http://schemas.datacontract.org/2004/07/MyDBService.Entity")]
    [System.SerializableAttribute()]
    public partial class Attractions : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _DescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal _unitPriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _Desc {
            get {
                return this._DescField;
            }
            set {
                if ((object.ReferenceEquals(this._DescField, value) != true)) {
                    this._DescField = value;
                    this.RaisePropertyChanged("_Desc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _ID {
            get {
                return this._IDField;
            }
            set {
                if ((object.ReferenceEquals(this._IDField, value) != true)) {
                    this._IDField = value;
                    this.RaisePropertyChanged("_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _Image {
            get {
                return this._ImageField;
            }
            set {
                if ((object.ReferenceEquals(this._ImageField, value) != true)) {
                    this._ImageField = value;
                    this.RaisePropertyChanged("_Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _Name {
            get {
                return this._NameField;
            }
            set {
                if ((object.ReferenceEquals(this._NameField, value) != true)) {
                    this._NameField = value;
                    this.RaisePropertyChanged("_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal _unitPrice {
            get {
                return this._unitPriceField;
            }
            set {
                if ((this._unitPriceField.Equals(value) != true)) {
                    this._unitPriceField = value;
                    this.RaisePropertyChanged("_unitPrice");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        EDP_Project.ServiceReference1.CompositeType GetDataUsingDataContract(EDP_Project.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<EDP_Project.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(EDP_Project.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectAttractionsAll", ReplyAction="http://tempuri.org/IService1/SelectAttractionsAllResponse")]
        EDP_Project.ServiceReference1.Attractions[] SelectAttractionsAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectAttractionsAll", ReplyAction="http://tempuri.org/IService1/SelectAttractionsAllResponse")]
        System.Threading.Tasks.Task<EDP_Project.ServiceReference1.Attractions[]> SelectAttractionsAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectAttractions", ReplyAction="http://tempuri.org/IService1/SelectAttractionsResponse")]
        EDP_Project.ServiceReference1.Attractions SelectAttractions(string ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectAttractions", ReplyAction="http://tempuri.org/IService1/SelectAttractionsResponse")]
        System.Threading.Tasks.Task<EDP_Project.ServiceReference1.Attractions> SelectAttractionsAsync(string ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateAttractions", ReplyAction="http://tempuri.org/IService1/CreateAttractionsResponse")]
        int CreateAttractions(string ID, string Name, string Desc, decimal unitPrice, string Image);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateAttractions", ReplyAction="http://tempuri.org/IService1/CreateAttractionsResponse")]
        System.Threading.Tasks.Task<int> CreateAttractionsAsync(string ID, string Name, string Desc, decimal unitPrice, string Image);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : EDP_Project.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<EDP_Project.ServiceReference1.IService1>, EDP_Project.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public EDP_Project.ServiceReference1.CompositeType GetDataUsingDataContract(EDP_Project.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<EDP_Project.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(EDP_Project.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public EDP_Project.ServiceReference1.Attractions[] SelectAttractionsAll() {
            return base.Channel.SelectAttractionsAll();
        }
        
        public System.Threading.Tasks.Task<EDP_Project.ServiceReference1.Attractions[]> SelectAttractionsAllAsync() {
            return base.Channel.SelectAttractionsAllAsync();
        }
        
        public EDP_Project.ServiceReference1.Attractions SelectAttractions(string ID) {
            return base.Channel.SelectAttractions(ID);
        }
        
        public System.Threading.Tasks.Task<EDP_Project.ServiceReference1.Attractions> SelectAttractionsAsync(string ID) {
            return base.Channel.SelectAttractionsAsync(ID);
        }
        
        public int CreateAttractions(string ID, string Name, string Desc, decimal unitPrice, string Image) {
            return base.Channel.CreateAttractions(ID, Name, Desc, unitPrice, Image);
        }
        
        public System.Threading.Tasks.Task<int> CreateAttractionsAsync(string ID, string Name, string Desc, decimal unitPrice, string Image) {
            return base.Channel.CreateAttractionsAsync(ID, Name, Desc, unitPrice, Image);
        }
    }
}
